#!/bin/sh
## Copyright 2017 Clemens Fruhwirth <clemens@endorphin.org>
##
## Usage: pwdjail-rmIr DIR
##
absolute() {
    cd $1 && pwd
}

# FIXME any modification to this function with master-zshrc
function pwdjail_get_user_for_directory() {
  getent passwd | awk -F: '"'"$1"/'" ~ $6"/" && $5 ~ "Sandbox user" { print $1 }' | head -1
}

SANDBOX_HOME=$(absolute $1)
if [ -z $SANDBOX_HOME ]; then
  (>&2 echo "Could not access $1.")
  exit 1
fi

SANDBOX_USER=$(pwdjail_get_user_directory "$SANDBOX_HOME")
if [ -z "$SANDBOX_USER" ]; then
  (>&2 echo "No user has $SANDBOX_HOME as home directory.")
  exit 1
fi

echo "$SANDBOX_USER owns $1. Removing..."
# FIXME killall processes belonging to this user, so that userdel succeeds.
sudo userdel $SANDBOX_USER
echo "Removed user."
echo "Calling \"rm -Ir $1\""
sudo rm -Ir $1
